site_name: FPSensor Home
site_url: https://fpsensor.github.io/

theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
  favicon: assets/favicon.ico
  logo: assets/logo.png
  name: material
  palette: 

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github

extra:
  homepage: https://fpsensor.github.io
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Spanish
      link: /es/
      lang: es

plugins:
  - search
  - blog:
      archive_date_format: MM/yyyy
      archive_url_date_format: MM/yyyy

nav:
  - index.md
  - Blog:
    - blog/index.md

repo_url: https://github.com/FPSensor
repo_name: FPSensor
